image: Visual Studio 2017
version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: production
  api_key:
    secure: X0+F7f/HkNyYuwpoiHHAckUU2ginH80c6nsz2xMcnOFBYjq78Ckjy7wSr0edqoAx
  on:
    branch: master
    appveyor_repo_tag: true